apiVersion: v1
kind: Secret
metadata:
    name: db-creds
    #namespace: eks-example
    namespace: flux-system
data:
    username: ENC[AES256_GCM,data:I6MBHyWeJW8=,iv:/DMIdrHgHNmDXNdwq9HTfJJZjZZ0IR9WAvFdTjFiJ9g=,tag:k3olI5YQGiTlG/sSVkoiPA==,type:str]
    password: ENC[AES256_GCM,data:48SLD1u1ucF/79z+RClh,iv:LDgUCWHEi1r5ZdpDzAbpHBS/BVKICkbfZIwFGCqhho0=,tag:MgNrlpY/5Jr7pmjp+IhSQw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:682651395775:key/9a634677-d037-455b-a413-80ceeba22b98
        created_at: '2020-11-03T02:57:07Z'
        enc: AQICAHgbRsMZYOPDUS4iW1ZqPjLKLbWnZXvN3bv0NN/hjow4MgHoE+/nZ+9q0K94YvL4IQF2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9sNQzAcfKHdBQBBRAgEQgDvDUiMHgGnwPEWD2sk+KJ84TD3r2PAsTVnDUFXfRDj4MT1lmd+FBluHBZJdwXOTu7kMjQIUUkxZ8We2+Q==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-03T02:57:07Z'
    mac: ENC[AES256_GCM,data:z9CrDkaqcpugcoFTzc1rQI9IbYXE6mmuu06u+s9sQCQtQkV4y8TR0dBXUOPujxAF0CEqFlqrmC6a7m0VUMXZd3Nl8KeZzKeL6HbsLyD8Y7L4mK0ZbxcZWXuehfvSAEybqDf1UFXsS6MyLG1Uw+GtolULT1ZOSzU9ATzShNr/w+E=,iv:mKpOH/YYxbfXBbhDhRDFgqSLgGrVy2H9Jn9iayxYLdo=,tag:5NQoIukjT7bkG27JoQiJzw==,type:str]
    pgp:
    -   created_at: '2020-11-05T16:20:22Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA2URRrx+O6WEAQgAGGgXsAEJnAjrwYwMkBh08Vr7YC21S4uXLkyWIVExQ01Y
            ZUGOU7PeBYU5NEoGcz0AYgaFGEZk98bz47dva6YjSwkhgnwn51AJEKh7oCVS30LF
            n90sVT86QPy5dl0JcfSn8bCK64vZobLPLmNjAeCjMCvNnISKpufYArbcQyahmbw6
            a6ncsbVZeI/OUUbFOKTH5Tw5ZS6/cS58I1vZN3/aLvT3U4gW95rnbWJBYUbEc7ih
            hz774nhI2F/0bAqOJ6vKHFuXRGoNpO3a/6X882/Ypi4yySza6Q4tsG4UnKSSttdM
            PGp0q+Opo4zVfJ3YcB6ELUp0S+RIJUemQlQbNzXrCNLgAeQOE0zTB9ROuIvAf8Sw
            7aRr4TuQ4OfgYuH/a+A54j2ijr7g5uVUbxqNSqHwYjaQCSkI1LbtpsbwmrvxvafD
            rLbo5EzQr+BR5GqfL4M4SVseSx75y0ifx+riq6E/7eFL4QA=
            =6w9Q
            -----END PGP MESSAGE-----
        fp: 0C7B4DF7B95CD700C6E1F131536F2CC3DC146EF8
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
